#ifndef _INCLUDED_ring_synapses_asym_pre_codeobject_1
#define _INCLUDED_ring_synapses_asym_pre_codeobject_1

void _run_ring_synapses_asym_pre_codeobject_1();

void _debugmsg_ring_synapses_asym_pre_codeobject_1();

#endif
