#ifndef _INCLUDED_ring_synapses_synapses_create_generator_codeobject
#define _INCLUDED_ring_synapses_synapses_create_generator_codeobject

void _run_ring_synapses_synapses_create_generator_codeobject();


#endif
