#ifndef _INCLUDED_ring_synapses_asym_pre_codeobject
#define _INCLUDED_ring_synapses_asym_pre_codeobject

void _run_ring_synapses_asym_pre_codeobject();

void _debugmsg_ring_synapses_asym_pre_codeobject();

#endif
